# Generated by Django 3.2.7 on 2021-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_pic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognize',
            name='tagname',
            field=models.CharField(default='1', max_length=20, verbose_name='tagname'),
        ),
    ]
