# Generated by Django 3.2.7 on 2021-09-05 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_pic', '0004_auto_20210901_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognize',
            name='stime',
            field=models.DateField(default=datetime.datetime(2021, 9, 5, 3, 10, 56, 11303), verbose_name='time'),
        ),
    ]
