# Generated by Django 3.2.7 on 2021-09-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_pic', '0005_recognize_stime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognize',
            name='stime',
            field=models.CharField(max_length=200, verbose_name='time'),
        ),
    ]
