name: build

on: [push, pull_request]

jobs:
  pwa:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test.ci

      - name: Build Ionic
        run: npm run build
