name: deploy

on:
  push:
    branches:
      - master

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install

      - name: Build Ionic
        run: ionic build --prod -- --base-href=/ionic-pwa-example-moment/

      - name: Deploy on GitHub pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: www
