name: release

on:
  push:
    branches:
      - master

jobs:
  gh-release:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Check if version has been updated
        id: version_check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: steps.version_check.outputs.changed == 'true'
        run: |
          npm install -g @ionic/cli
          npm install

      - name: Build Ionic
        if: steps.version_check.outputs.changed == 'true'
        run: npm run build

      - name: Zip build files
        if: steps.version_check.outputs.changed == 'true'
        run: zip -r -9 build.zip ./www/

      - name: GitHub release
        if: steps.version_check.outputs.changed == 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.version_check.outputs.version }}
          tag_name: ${{ steps.version_check.outputs.version }}
          body: Thanks for following along! For more information check out the [CHANGELOG](https://github.com/seanwu1105/ionic-pwa-example-moment/blob/master/CHANGELOG.md).
          files: build.zip
